name: CI/CD
on:
  workflow_dispatch:
    inputs:
      needdeploy:
        description: 'Need to push to Docker Registry?'
        required: true
        default: 'yes'
        type: choice
        options:
        - yes
        - no
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          if: github.event.inputs.needdeploy == 'yes'
          push: true
          tags: cyberdanus/my_app:${{  steps.vars.outputs.short_sha  }}
      - name: Docker pull image
        run: docker pull cyberdanus/my_app:${{  steps.vars.outputs.short_sha  }}
      - name: Docker deploy latest image from Docker Registry
        run: docker run -p 3000:3000 -d cyberdanus/my_app:${{  steps.vars.outputs.short_sha  }}
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
  pull:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
  deploy:
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
