name: Test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: user/app:latest
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
  pull:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
  deploy:
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
                
