name: CI/CD
on:
  workflow_dispatch:
    inputs:
      needdeploy:
        description: 'Need to push to Docker Registry?'
        required: true
        default: '(Yes)'
        type: choice
        options:
        - (Yes)
        - (No)
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          if: github.event.inputs.needdeploy == '(Yes)'
          push: true
          tags: cyberdanus/my_app:${{  steps.vars.outputs.short_sha  }}
      - name: Docker pull image
        if: github.event.inputs.needdeploy == '(Yes)'
        run: docker pull cyberdanus/my_app:${{  steps.vars.outputs.short_sha  }}
      - name: Docker deploy latest image from Docker Registry
        if: github.event.inputs.needdeploy == '(Yes)'
        run: docker run -p 3000:3000 -d cyberdanus/my_app:${{  steps.vars.outputs.short_sha  }}

