name: Test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
  pull:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
                
