name: CI/CD
on:
  workflow_dispatch:
    inputs:
      needdeploy:
        description: 'Need to push to Docker Registry?'
        required: true
        default: '(Yes)'
        type: choice
        options:
        - (Yes)
        - (No)
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Run script from Scripts repo 
      #   run: ./.github/scripts/build.sh
      #   shell: bash
      - name: Download the script
        run: curl -o $PWD/script.sh https://raw.githubusercontent.com/cyberdanus/scripts/main/script.sh
      - name: Give script permissions
        run: chmod +x $PWD/script.sh
      - name: Execute script
        # run: $PWD/script.sh env.txt
        run: |
          echo "docker_repo=$(bash $PWD/script.sh)" >> $GITHUB_ENV
          echo "${{ env.docker_repo }}
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"
      - name: Build and push
        if: github.event.inputs.needdeploy == '(Yes)'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: cyberdanus/my_app:${{  steps.vars.outputs.short_sha  }}
      - name: Docker pull image
        if: github.event.inputs.needdeploy == '(Yes)'
        run: docker pull cyberdanus/my_app:${{  steps.vars.outputs.short_sha  }}
      - name: Docker deploy latest image from Docker Registry
        if: github.event.inputs.needdeploy == '(Yes)'
        run: docker run -p 3000:3000 -d cyberdanus/my_app:${{  steps.vars.outputs.short_sha  }}

